name: Build FNF iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install Haxe via Homebrew
        run: |
          brew install haxe
          haxelib setup ~/haxelib

      - name: Install Base Dependencies
        run: |
          haxelib install lime 8.0.1
          haxelib install openfl 9.3.3
          haxelib install flixel 5.5.0
          haxelib install flixel-addons 3.2.1
          haxelib install flixel-ui 2.5.0
          haxelib install hscript
          haxelib install hxcpp
          haxelib run lime setup

      - name: Install Psych Engine Specific Libraries
        run: |
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git hxDiscordRpc https://github.com/Aidan63/hxDiscordRpc
          haxelib git SlayEngine https://github.com/ShadowMario/SlayEngine

      - name: Build iOS
        run: |
          haxelib run lime build ios -nosign

      - name: Make IPA
        run: |
          mkdir -p Payload
          cp -r export/release/ios/build/Release-iphoneos/*.app Payload/
          zip -r FNF-Game.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: FNF-Game-iOS
          path: FNF-Game.ipa
